### ISSUE TITLE
Unable to implement GitLab OAuth2

### ISSUE THREAD

**Issue by UYJ4uc3YRjCKCiKwp0qO** [leihs/leihs-zhdk-agw-auth-system#11]
I would like to use the OAuth2 interface from GitLab for authentication to the leihs system.
Due to the lack of documentation I was unable to do so.
Is there any documentation or tutorial which shows, how to do?
Also I'm not sure, if OAuth2 is completely supported for the leihs-zhdk-agw-auth-system or if the zhdk agw auth system is just based on OAuth2.
Is there any additional deployment process necessary to implement this? If yes, how to deploy the additional leihs-zhdk-agw-auth-system so OAuth2 works fine with GitLab?
By filling out the fields in the "Add external Authentication-System" I always get the error  " Request "Add Authentication-System" ERROR 409

The message sent with the response says:

ERROR: new row for relation "authentication_systems" violates check constraint "check_valid_type""

Thank you!

**Comment by DrTom** [comment]
Please have a look at https://github.com/leihs/leihs/wiki/external_authentication

Further issues via https://github.com/leihs/leihs/issues
